"""
Network Latency Experiments
Introduce latency and jitter between frontend and backend.
"""

---
# Network Latency - Add 200ms latency with jitter
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-latency-high
  namespace: chaos-demo
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - chaos-demo
    labelSelectors:
      app: frontend
  delay:
    latency: "200ms"
    correlation: "20"
    jitter: "50ms"
  direction: to
  target:
    selector:
      namespaces:
        - chaos-demo
      labelSelectors:
        app: backend
    mode: all
  duration: "3m"
